dist: xenial

language: go

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

notifications:
  email: false

go:
  - 1.14.x
  - 1.15.x
  - master

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled